### ISSUE TITLE
Can I use custom color?

### ISSUE THREAD

**Issue by Karina1703** [thillmann/tailwindcss-bg-patterns#3]
I want to use my custom color, how can I do it?

**Comment by thillmann** [comment]
Yes, the plugin picks up the colours defined in your tailwindcss theme! 

For example, if you are adding a custom colour to your theme like this:

```javascript
module.exports = {
  plugins: [require("tailwindcss-bg-patterns")],
  theme: {
    extend: {
      colors: {
        "custom-color": {
          400: "red",
        },
      },
    },
  },
};
```

You can then use it like this:

```html
<div class="pattern-zigzag pattern-custom-color-400 pattern-bg-white "></div>
```

This also works for the background colour (e.g., `pattern-bg-custom-color`).
